Разметка внутренней страницы
htmlacademy-htmlcss/1552835-technomart-29 pull request #3
Opened 2020-09-15 20:01 UTC by V-Donut

2020-09-15 21:39 UTC, SidSpears69 requested changes

2020-09-15 21:39 UTC, SidSpears69 commented on catalog.html
> +              <p>
Точно ли нужна обертка изображению?

2020-09-15 21:39 UTC, SidSpears69 commented on catalog.html
> +            <p>
Цены разделены стилистически и по смыслу, лучше разделить их и в верстке

2020-09-16 05:31 UTC, V-Donut commented on catalog.html
> +            <p>
А как правильно разделить их по смыслу?  Первую цену можно в тег <p>, а вторую в <div>? Или в разные теги <p>?

2020-09-16 09:01 UTC, V-Donut commented on catalog.html
> +              <p>
Исправила

2020-09-16 09:02 UTC, V-Donut commented on catalog.html
> +            <p>
Разделила цены

2020-09-16 14:41 UTC, merged